version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: daily-scribe-prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./monitoring/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts:/etc/prometheus/alerts
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - daily-scribe-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: daily-scribe-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - daily-scribe-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.0
    container_name: daily-scribe-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - daily-scribe-network
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: daily-scribe-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/config/loki.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - daily-scribe-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    container_name: daily-scribe-promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/config/promtail.yml:/etc/promtail/config.yml
      - daily_scribe_cron_logs:/app/cron-logs:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - daily-scribe-network
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  daily_scribe_cron_logs:
    external: true
    name: daily-scribe_daily_scribe_cron_logs

networks:
  daily-scribe-network:
    external: true
