version: '3.8'

services:
  # Daily Scribe FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: daily-scribe:latest
    container_name: daily-scribe-app
    restart: unless-stopped
    environment:
      - DB_PATH=/data/digest_history.db
      - DB_TIMEOUT=${DB_TIMEOUT:-30}
      - FRONTEND_URL=${FRONTEND_URL:-https://dailyscribe.news}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-aws_ses}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER:-email-smtp.us-east-1.amazonaws.com}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT:-587}
      - EMAIL_SMTP_USERNAME=${EMAIL_SMTP_USERNAME}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_AWS_REGION=${EMAIL_AWS_REGION:-us-east-1}
      - EMAIL_FROM_EDITOR=${EMAIL_FROM_EDITOR:-editor@dailyscribe.news}
      - EMAIL_FROM_ADMIN=${EMAIL_FROM_ADMIN:-admin@dailyscribe.news}
      - EMAIL_FROM_SUPPORT=${EMAIL_FROM_SUPPORT:-support@dailyscribe.news}
      - EMAIL_RATE_LIMIT=${EMAIL_RATE_LIMIT:-14}
      - EMAIL_RETRY_ATTEMPTS=${EMAIL_RETRY_ATTEMPTS:-3}
      - EMAIL_TIMEOUT=${EMAIL_TIMEOUT:-30}
      - PYTHONPATH=/app/src:/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./data:/data:Z
      - daily_scribe_logs:/var/log/daily-scribe
      - ./config.json:/app/config.json:ro
    networks:
      - daily_scribe_internal
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["python", "-m", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]

  # Daily Scribe Cron Jobs
  cron:
    build:
      context: .
      dockerfile: cron/Dockerfile
    image: daily-scribe-cron:latest
    container_name: daily-scribe-cron
    restart: unless-stopped
    environment:
      - DB_PATH=/data/digest_history.db
      - FRONTEND_URL=${FRONTEND_URL:-https://dailyscribe.news}
      - DB_TIMEOUT=${DB_TIMEOUT:-30}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER:-aws_ses}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER:-email-smtp.us-east-1.amazonaws.com}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT:-587}
      - EMAIL_SMTP_USERNAME=${EMAIL_SMTP_USERNAME}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_AWS_REGION=${EMAIL_AWS_REGION:-us-east-1}
      - EMAIL_FROM_EDITOR=${EMAIL_FROM_EDITOR:-editor@dailyscribe.news}
      - EMAIL_FROM_ADMIN=${EMAIL_FROM_ADMIN:-admin@dailyscribe.news}
      - EMAIL_FROM_SUPPORT=${EMAIL_FROM_SUPPORT:-support@dailyscribe.news}
      - EMAIL_RATE_LIMIT=${EMAIL_RATE_LIMIT:-14}
      - EMAIL_RETRY_ATTEMPTS=${EMAIL_RETRY_ATTEMPTS:-3}
      - EMAIL_TIMEOUT=${EMAIL_TIMEOUT:-30}
      - PYTHONPATH=/app/src:/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=${TZ:-UTC}
    volumes:
      - ./data:/data:Z
      - daily_scribe_logs:/var/log/daily-scribe
      - daily_scribe_cron_logs:/var/log/cron
      - ./config.json:/app/config.json:ro
    networks:
      - daily_scribe_internal
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "which", "supercronic"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Database Administration Tool
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: daily-scribe-cloudbeaver
    restart: unless-stopped
    ports:
      - "8080:8978"
    volumes:
      - ./data:/opt/cloudbeaver/data  # Read-write access to database files
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    environment:
      - CB_SERVER_NAME=Daily Scribe Database
    networks:
      - daily_scribe_internal
    depends_on:
      - app
    profiles:
      - admin

# Named volumes for data persistence
volumes:
  daily_scribe_logs:
    driver: local
  daily_scribe_cron_logs:
    driver: local
  cloudbeaver_workspace:
    driver: local

# Networks for service isolation and communication
networks:
  daily_scribe_internal:
    driver: bridge
    internal: false
