version: '3.8'

# Development overrides for Docker Compose
# This file is automatically loaded by Docker Compose when present
# Use: docker-compose up -f docker-compose.yml -f docker-compose.override.yml

services:
  # Development overrides for the app service
  app:
    # Enable hot reloading and development mode
    command: ["python", "-m", "uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for hot reloading (extends base volumes)
      - ./src:/app/src
      - ./tests:/app/tests

  # Development overrides for cron service
  cron:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for development (extends base volumes)
      - ./src:/app/src


  # Litestream development configuration
  litestream:
    # For development, use mock configuration to test without real GCS
    environment:
      - GCS_BUCKET=development-mock-bucket
      - GCS_REGION=us-central1
      # Use example service account for testing
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcs/service-account-example.json
    volumes:
      # Mount example service account for development testing
      - ./gcs-service-account.json.example:/etc/gcs/service-account-example.json:ro
    # Keep container running but with less aggressive health checks
    healthcheck:
      interval: 60s
      timeout: 15s
      retries: 2
    # Uncomment to disable Litestream in development
    # command: ["echo", "Litestream disabled in development - using local database only"]
    # restart: "no"

# Development volumes - simplified to avoid conflicts
volumes:
  # Remove the bind mount override to use the main configuration
  daily_scribe_data: {}

# Development network configuration
networks:
  daily_scribe_internal:
    # Enable external connectivity for development debugging
    internal: false
