global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'daily-scribe@localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  email_configs:
  - to: 'admin@localhost'
    subject: 'Daily Scribe Alert'
    body: 'Alert triggered'
